<?php

namespace HelpiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use HelpiBundle\Entity\Message;
use HelpiBundle\Entity\User;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    public function save(Message $message){
        $this->getEntityManager()->persist($message);
        $this->getEntityManager()->flush();
    }
    /*
    public function usernameToId($username){

      //  $repoUser = $this->getDoctrine()->getRepository('HelpiBundle:User');
        $user=$this->findByUsername($username);
        return $user->getId();


    }*/


}
